/*
 *
 *Acquire
 *
 *This is a license header!!! :D
 *
 *
 *
 */
package com.flyingblock.acquire.network;

import com.flyingblock.acquire.computer.Decider;
import com.flyingblock.acquire.computer.RandomDecider;
import com.flyingblock.acquire.controller.AcquireRules;
import com.flyingblock.acquire.model.AcquireBoard;
import com.flyingblock.acquire.model.Corporation;
import com.flyingblock.acquire.model.Game;
import com.flyingblock.acquire.model.Hotel;
import com.flyingblock.acquire.model.HotelMarket;
import com.flyingblock.acquire.model.Investor;
import com.flyingblock.acquire.model.Location;

import java.awt.Color;
import java.io.IOException;
import java.net.Socket;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Nick_Pro
 */
public class ChatLobbyServer extends javax.swing.JFrame implements ServerListener {

    private Map<Socket, String> names;
    private List<Socket> pendingConnections;
    private Server server;
    private AcquireServer acquireGame;
    /**
     * Creates new form ChatLobbyServer
     */
    public ChatLobbyServer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        portInputField = new javax.swing.JTextField();
        startButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        chatInputField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        usersTextArea = new javax.swing.JTextArea();
        gameStart = new javax.swing.JButton();
        playerNumberField = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acquire Server");
        setResizable(false);

        jLabel1.setText("Port");

        portInputField.setText("Port");
        portInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portInputFieldActionPerformed(evt);
            }
        });

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        stopButton.setText("Stop");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        chatInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatInputFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Input field");

        jLabel3.setText("Chat");

        jLabel4.setText("Online Users");

        jLabel5.setText("Server Options");

        jLabel6.setText("Max Players");

        chatTextArea.setEditable(false);
        chatTextArea.setColumns(20);
        chatTextArea.setLineWrap(true);
        chatTextArea.setRows(5);
        jScrollPane1.setViewportView(chatTextArea);

        usersTextArea.setEditable(false);
        usersTextArea.setColumns(20);
        usersTextArea.setRows(5);
        jScrollPane2.setViewportView(usersTextArea);

        gameStart.setText("StartGame");
        gameStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameStartActionPerformed(evt);
            }
        });

        playerNumberField.setModel(new javax.swing.SpinnerNumberModel(4, 2, 6, 1));
        playerNumberField.setToolTipText("");
        playerNumberField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        playerNumberField.setFocusable(false);
        playerNumberField.setName(""); // NOI18N
        playerNumberField.setRequestFocusEnabled(false);
        playerNumberField.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                playerNumberFieldStateChanged(evt);
            }
        });
        playerNumberField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                playerNumberFieldPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(startButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stopButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(portInputField, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(playerNumberField)))
                    .addComponent(gameStart))
                .addGap(164, 164, 164)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(22, 22, 22))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(29, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(chatInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(portInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(playerNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startButton)
                    .addComponent(stopButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chatInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gameStart))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void portInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portInputFieldActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        pendingConnections = new ArrayList<>();
        if(server == null || !server.isRunning())
        {
            try {
                int port = Integer.parseInt(portInputField.getText());
                server = new Server(port);
                server.addListener(this);
                displayMessage("Starting server");
                new Thread(){
                    @Override
                    public void run()
                    {
                        updateOnlineUsers();
                        try {
                            server.start();
                        } catch (IOException ex) {
                            displayMessage(ex.toString());
                        }
                    }
                }.start();
                names = new HashMap<>();
                if(acquireGame != null)
                {
                    acquireGame.stop();
                    acquireGame = null;
                }
            }
            catch (NumberFormatException ex)
            {
                displayMessage("Your port number is not valid");
            }
        }
        if(server != null && server.isRunning())
        {
            displayMessage("The server is already running");
        }
    }//GEN-LAST:event_startButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        // TODO add your handling code here:
        if(server != null && server.isRunning())
        {
            try {
                server.stop();
                updateOnlineUsers();
            } catch (IOException ex) {
                Logger.getLogger(ChatLobbyServer.class.getName()).log(Level.SEVERE, null, ex);
            }
            displayMessage("Server has been stopped");
        }
        else
        {
            displayMessage("Server is not running");
        }
    }//GEN-LAST:event_stopButtonActionPerformed

    private void chatInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatInputFieldActionPerformed
        // TODO add your handling code here:
        sendChatEvent("SERVER", chatInputField.getText());
        chatInputField.setText("");
    }//GEN-LAST:event_chatInputFieldActionPerformed

    private void gameStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameStartActionPerformed
        // TODO add your handling code here:
        //start game
        //System.out.println(acquireGame);
        if(acquireGame == null)
        {
            //kick all pending connections
            for(Socket pending : pendingConnections) {
                server.getClient(pending).disconnect();
            }
            //Setup the game
            List<String> humanNames = new ArrayList<>();
            for(Entry<Socket, String> entry : names.entrySet())
                humanNames.add(entry.getValue());
            //Construct the investors
            List<String> investors = new ArrayList<>();
            investors.addAll(humanNames);
            investors.addAll(AcquireRules.getRandomNames(getMaxPlayers() - humanNames.size(), humanNames));
            List<Investor> players = new ArrayList<>();
            for(int i = 0; i < getMaxPlayers(); i++)
            {
                Investor investor = new Investor(investors.get(i), 6000, 6, Color.RED);
                players.add(investor);
            }
            Game game = new Game(players);
            List<Corporation> companies = new ArrayList<>();
            for(int i = 0; i < game.getNumCorporations(); i++)
                companies.add(game.getCorporation(i));
            List<Decider> computers = new ArrayList<>();
            List<NetInvestor> networkedPlayers = new ArrayList<>();
            for(ClientThread client : server.getClients())
            {
                Investor i = players.get(0);
                for(Investor player : players)
                {
                    if(player.getName().equals(names.get(client.getSocket())))
                        i = player;
                }
                networkedPlayers.add(new NetInvestor(i, client));
            }
            for(int i = humanNames.size(); i < getMaxPlayers(); i++)
            {
                List<Investor> opponents = new ArrayList<>(players);
                opponents.remove(i);
                computers.add(new RandomDecider(players.get(i), game.getGameBoard(), companies, opponents));
            }
            Collections.shuffle(players);
            GameEvent startingEvent = EventType.createEvent(EventType.GAME_START, 
                    new Object[]{players.toArray(new Investor[players.size()]),
                    game.getGameBoard(), companies.toArray(new Corporation[companies.size()])});
            game.getMarket().shuffle();
            //game.getGameBoard().set(0,0,new Hotel(new Location(0,0)));
            
            for(ClientThread thread : server.getClients())
            {
                thread.sendData(startingEvent);
            }
            
            acquireGame = new AcquireServer(server, computers, networkedPlayers,
                players, game.getGameBoard(), companies, game.getMarket(), 100);
            
            this.sendChatEvent("Server", "Game starting in 1 second");
            
            acquireGame.start();
        }
        else
            displayMessage("Game has already started");
    }//GEN-LAST:event_gameStartActionPerformed

    private void playerNumberFieldStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_playerNumberFieldStateChanged
        // TODO add your handling code here:
        int max = (Integer)playerNumberField.getValue();
        if(names != null && max < names.values().size())
        {
            max = names.values().size();
            playerNumberField.setValue(max);
        }
    }//GEN-LAST:event_playerNumberFieldStateChanged

    private void playerNumberFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_playerNumberFieldPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_playerNumberFieldPropertyChange

    public void displayMessage(String message)
    {
        if(!chatTextArea.getText().isEmpty())
            chatTextArea.append("\n" + message);
        else
            chatTextArea.append(message);
        chatTextArea.setCaretPosition(chatTextArea.getDocument().getLength());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatLobbyServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatLobbyServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatLobbyServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatLobbyServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatLobbyServer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField chatInputField;
    private javax.swing.JTextArea chatTextArea;
    private javax.swing.JButton gameStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner playerNumberField;
    private javax.swing.JTextField portInputField;
    private javax.swing.JButton startButton;
    private javax.swing.JButton stopButton;
    private javax.swing.JTextArea usersTextArea;
    // End of variables declaration//GEN-END:variables


    public void updateOnlineUsers()
    {
        String str = "";
        for(String name : names.values())
        {
            str += name + "\n";
        }
        for(Socket pending : pendingConnections)
        {
            str += pending.getInetAddress() + " pending...\n";
        }
        usersTextArea.setText(str);
    }
    
    @Override
    public void objectRecieved(Socket client, Object message) 
    {
        if(!names.containsKey(client) && message instanceof String)
        {
            String name = ((String) message).toUpperCase().trim();
            if(names.containsValue(name))
            {
                server.getClient(client).sendData("That name is already taken, choose a new one");
            }
            else
            {
                names.put(client, name);
                server.getClient(client).sendData(EventType.createEvent(EventType.NAME_GIVEN, name));
                sendChatEvent(names.get(client), "Has joined the server");
                pendingConnections.remove(client);
                updateOnlineUsers();
                if(names.size() >= getMaxPlayers())
                {
                    for(Socket connection : pendingConnections)
                    {
                        ClientThread thread = server.getClient(connection);
                        thread.sendData("Server is full, sorry");
                        thread.disconnect();
                    }
                }
            }
        }
        else if(names.containsKey(client) && message instanceof String)
        {
            String line = (String) message;
            if(line.startsWith("/"))
            {
                //do command
            }
            else
            {
                sendChatEvent(names.get(client), line);
            }
        }
    }
    
    public void sendChatEvent(String sender, String message)
    {
        Set<ClientThread> clients = server.getClients();
        String thingy = "[" + sender + "] " + message;
        for(ClientThread c : clients)
        {
            c.sendData(thingy);
        }
        displayMessage(thingy);
    }

    @Override
    public void joinedNetwork(Socket client) 
    {
        ClientThread thread = server.getClient(client);
        if(names.size() >= getMaxPlayers())
        {
            thread.sendData("The game is full, sorry");
            thread.disconnect();
        }
        else
        {
            //System.out.println(client + " joined the network");
            pendingConnections.add(client);
            thread.sendData("Please tell us your name");
            updateOnlineUsers();
        }
    }

    public int getMaxPlayers()
    {
        return (Integer)playerNumberField.getValue();
    }
    
    @Override
    public void disconnectedFromNetwork(Socket client) 
    {
        if(names.containsKey(client))
            sendChatEvent("SERVER", names.get(client) + " has left the server");
        names.remove(client);
        pendingConnections.remove(client);
        updateOnlineUsers();
    }

    @Override
    public void connectionRejected(Socket client) 
    {
        
    }

}
